name: healthsync
services:
  restapi:
    build:
      context: .
      dockerfile: RestAPI/Dockerfile
    image: healthsync-restapi
    container_name: restapi
    ports:
      - "8081:8081"
      - "8080:8080"
    depends_on:
      - sql_server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/healthsync.pfx
    networks:
      - app-network
    volumes:
      - ~/.aspnet/https:/https:ro 
      - ./Infrastructure/Services/Configs/gcp-credentials-service-account.json:/app/Infrastructure/Services/Configs/gcp-credentials-service-account.json:ro

  frontend:
    build:
      context: .
      dockerfile: Client/Dockerfile
    image: healthsync-frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - restapi
    networks:
      - app-network

  sql_server:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: database
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=mlEVg137l73S7YNH
    ports:
      - "1433:1433"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
