name: healthsync
services:
  restapi:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: healthsync-restapi
    container_name: restapi
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    networks:
      - app-network
    depends_on:
      - postgresql

  frontend:
    build:
      context: .
      dockerfile: Client/Dockerfile.dev
    image: healthsync-frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8080
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - restapi
    networks:
      - app-network

  postgresql:
    image: postgres:15
    container_name: database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mlEVg137l73S7YNH
      POSTGRES_DB: healthsync
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
