name: healthsync
services:
  restapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: healthsync-restapi
    container_name: restapi
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    networks:
      - app-network
    depends_on:
      - sqlserver

  frontend:
    build:
      context: .
      dockerfile: Client/Dockerfile
    image: healthsync-frontend
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - restapi
    networks:
      - app-network

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: database
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "mlEVg137l73S7YNH"
    ports:
      - "1433:1433"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
