# fly.toml app configuration file generated for healthsync-restapi on 2025-04-13T16:09:43+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'healthsync-restapi'
primary_region = 'fra'

[build]
  dockerfile = 'RestAPI/Dockerfile'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'stop'
  auto_start_machines = true
  ports = []
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
